# This is a basic workflow to help you get started with Actions

name: Publish Starters

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    branches: [main]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: starters Hyperobjekt name master
